### ISSUE TITLE
How to add IJSRuntime

### ISSUE THREAD

**Issue by Sridhar-Narasimhan** [SteveSandersonMS/BlazorUnitTestingPrototype#4]
How we can add IJSRuntime to the library to test Blazor components which have interaction through JavaScript interop.

**Comment by SteveSandersonMS** [comment]
You should supply a mock implementation of `IJSRuntime` that accepts whatever calls your component makes, and gives whatever responses are needed to simulate the scenarios you're testing.

You can't actually execute JavaScript, since that would involve a real browser. One of the primary goals of this testing system is to avoid involving real browsers.

**Comment by matthewpetch** [comment]
@SteveSandersonMS could you update the sample project with an example of this please?

**Comment by SteveSandersonMS** [comment]
@matthewpetch I'm not in a position to do that any time soon as I'm working on other priorities. In general you can use something like Moq to supply a mock implementation of `IJSRuntime`. Naturally this is something that would end up being discussed clearly in docs and samples if we turn this unit testing prototype into a supported feature.
